# Generated by Django 4.0.3 on 2022-04-19 13:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='weapon',
            name='alternative2',
            field=models.CharField(blank=True, default=None, max_length=512, null=True),
        ),
    ]
