# Generated by Django 4.0.5 on 2023-02-17 18:32

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0001_initial'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Weapon',
            new_name='Weapon_w1',
        ),
    ]
