# Generated by Django 4.0.5 on 2023-02-18 22:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0002_rename_weapon_weapon_w1'),
    ]

    operations = [
        migrations.AddField(
            model_name='command',
            name='updated_on',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='command',
            name='warzone_version',
            field=models.CharField(blank=True, default=None, max_length=2, null=True),
        ),
        migrations.AddField(
            model_name='lobby',
            name='updated_on',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='weapon_w1',
            name='updated_on',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
