# Generated by Django 4.0.5 on 2023-02-19 17:40

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0003_command_updated_on_command_warzone_version_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='weapon_w1',
            name='command',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='commands_w1', to='api.command'),
        ),
        migrations.CreateModel(
            name='Weapon_W2',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('category', models.CharField(max_length=50)),
                ('name', models.CharField(max_length=50, unique=True)),
                ('muzzle', models.CharField(blank=True, default=None, max_length=100, null=True)),
                ('barrel', models.CharField(blank=True, default=None, max_length=100, null=True)),
                ('laser', models.CharField(blank=True, default=None, max_length=100, null=True)),
                ('optic', models.CharField(blank=True, default=None, max_length=100, null=True)),
                ('stock', models.CharField(blank=True, default=None, max_length=100, null=True)),
                ('underbarrel', models.CharField(blank=True, default=None, max_length=100, null=True)),
                ('magazine', models.CharField(blank=True, default=None, max_length=100, null=True)),
                ('ammunition', models.CharField(blank=True, default=None, max_length=100, null=True)),
                ('reargrip', models.CharField(blank=True, default=None, max_length=100, null=True)),
                ('guard', models.CharField(blank=True, default=None, max_length=100, null=True)),
                ('comb', models.CharField(blank=True, default=None, max_length=100, null=True)),
                ('receiver', models.CharField(blank=True, default=None, max_length=100, null=True)),
                ('alternative', models.CharField(blank=True, default=None, max_length=512, null=True)),
                ('alternative2', models.CharField(blank=True, default=None, max_length=512, null=True)),
                ('updated_on', models.DateTimeField(blank=True, null=True)),
                ('command', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='commands_w2', to='api.command')),
            ],
        ),
    ]
