# Generated by Django 4.0.5 on 2023-02-19 17:48

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0004_alter_weapon_w1_command_weapon_w2'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Weapon_w1',
            new_name='WeaponW1',
        ),
        migrations.RenameModel(
            old_name='Weapon_W2',
            new_name='WeaponW2',
        ),
    ]
