# Generated by Django 4.0.5 on 2023-02-23 14:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0005_rename_weapon_w1_weaponw1_rename_weapon_w2_weaponw2'),
    ]

    operations = [
        migrations.AddField(
            model_name='command',
            name='identity_name_version',
            field=models.CharField(blank=True, max_length=100, null=True, unique=True),
        ),
        migrations.AlterField(
            model_name='command',
            name='name',
            field=models.CharField(max_length=50),
        ),
    ]
